apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: 502207623589.dkr.ecr.us-east-1.amazonaws.com/terraform-demo:tagVersion
      ports:
        - containerPort: 8090
